[tool.poetry]
name = "course_work_5_DB"
version = "0.1.0"
description = "HH Vacancies Project"

[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = "^2.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

